views/admin.py
from facades import AdministratorFacade, FacadeBase
from facades.functions import (
    get_country_name_by_id,
    get_user_by_user_id,
    get_user_by_username,
    get_user_role,
    get_user_role_id_by_role_name,
)
from flask import Blueprint, redirect, render_template, request, session, url_for

admin_page = Blueprint("admin_page", __name__, template_folder="../templates")

facade_base = FacadeBase()


@admin_page.route("/portal", methods=["GET", "POST"])
def portal():
    login_token = session.get("login_token")
    countries = facade_base.get_all_countries()
    airlines = None
    administrators = None
    customers = None

    if login_token:
        current_user_role = get_user_role(login_token)
        admin_facade = AdministratorFacade(login_token=login_token)
        airlines = admin_facade.get_all_airlines()
        administrators = admin_facade.get_all_administrators()
        customers = admin_facade.get_all_customers()
        current_logged_in_admin = admin_facade._user_data["id"]
        user = get_user_by_username(admin_facade._user_data["username"])
    else:
        error = "You must be logged in to perform this operation"
        return redirect(
            url_for(
                "index_page.login",
                error=error,
            )
        )
    return render_template(
        "admin_portal.html",
        current_user_role=current_user_role,
        countries=countries,
        airlines=airlines,
        administrators=administrators,
        customers=customers,
        user=user,
        get_user_by_user_id=get_user_by_user_id,
        current_logged_in_admin=current_logged_in_admin,
        get_country_name_by_id=get_country_name_by_id,
    )


# add route for adding a new country
@admin_page.route("/add-country", methods=["POST"])
def add_country():
    login_token = session.get("login_token")
    admin_facade = None

    if login_token:
        admin_facade = AdministratorFacade(login_token=login_token)
        country_name = request.form.get("name")
        country_flag = request.files.get("country-flag")

        admin_facade.add_country(country_name, country_flag)
        return redirect(url_for("admin_page.portal"))
    else:
        error = "You must be logged in to perform this operation"
        return redirect(
            url_for(
                "index_page.login",
                error=error,
            )
        )


# add route for adding a new airline
@admin_page.route("/add-airline", methods=["POST"])
def add_airline():
    login_token = session.get("login_token")
    admin_facade = None

    if login_token:
        admin_facade = AdministratorFacade(login_token=login_token)
        airline_name = request.form.get("name")
        airline_country_id = request.form.get("country_id")
        username = request.form.get("username")
        password = request.form.get("password")
        email = request.form.get("email")
        airline_logo = request.files.get("airline-logo")
        user_role_id = get_user_role_id_by_role_name("Airline")

        # create the user first
        user = admin_facade.create_new_user(
            username=username,
            password=password,
            email=email,
            user_role=user_role_id,
            photo_filename=airline_logo.filename if airline_logo else None,
            photo_data=airline_logo.read() if airline_logo else None,
        )

        # then create the airline
        admin_facade.add_airline(
            name=airline_name, country_id=airline_country_id, user_id=user.id
        )
        return redirect(url_for("admin_page.portal"))
    else:
        error = "You must be logged in to perform this operation"
        return redirect(
            url_for(
                "index_page.login",
                error=error,
            )
        )


# add route for adding a new administrator
@admin_page.route("/add-administrator", methods=["POST"])
def add_admin():
    login_token = session.get("login_token")
    admin_facade = None

    if login_token:
        admin_facade = AdministratorFacade(login_token=login_token)
        firstname = request.form.get("admin-firstname")
        lastname = request.form.get("admin-lastname")
        admin_photo = request.files.get("admin-photo")
        username = request.form.get("username")
        password = request.form.get("password")
        email = request.form.get("email")
        user_role_id = get_user_role_id_by_role_name("Administrator")

        # create the user first
        user = admin_facade.create_new_user(
            username=username,
            password=password,
            email=email,
            user_role=user_role_id,
            photo_filename=admin_photo.filename if admin_photo else None,
            photo_data=admin_photo.read() if admin_photo else None,
        )

        # then create the administrator
        admin_facade.add_administrator(
            firstname=firstname, lastname=lastname, user_id=user.id
        )
        return redirect(url_for("admin_page.portal"))
    else:
        error = "You must be logged in to perform this operation"
        return redirect(
            url_for(
                "index_page.login",
                error=error,
            )
        )


# add route for adding a new customer
@admin_page.route("/add-customer", methods=["POST"])
def add_customer():
    login_token = session.get("login_token")
    admin_facade = None

    if login_token:
        admin_facade = AdministratorFacade(login_token=login_token)
        firstname = request.form.get("firstname")
        lastname = request.form.get("lastname")
        username = request.form.get("username")
        password = request.form.get("password")
        email = request.form.get("email")
        address = request.form.get("address")
        customer_photo = request.files.get("customer-photo")
        phone_no = request.form.get("customer-phone-no")
        credit_card_no = request.form.get("credit_card_no")

        user_role_id = get_user_role_id_by_role_name("Customer")

        # create the user first
        user = admin_facade.create_new_user(
            username=username,
            password=password,
            email=email,
            user_role=user_role_id,
            photo_filename=customer_photo.filename if customer_photo else None,
            photo_data=customer_photo.read() if customer_photo else None,
        )

        # then create the airline
        admin_facade.add_customer(
            firstname=firstname,
            lastname=lastname,
            address=address,
            phone_no=phone_no,
            credit_card_no=credit_card_no,
            user_id=user.id,
        )
        return redirect(url_for("admin_page.portal"))
    else:
        error = "You must be logged in to perform this operation"
        return redirect(
            url_for(
                "index_page.login",
                error=error,
            )
        )


# add route for removing a country
@admin_page.route("/remove-country")
def remove_country():
    login_token = session.get("login_token")
    country_id = int(request.values.get("country_id"))
    admin_facade = None

    if login_token:
        admin_facade = AdministratorFacade(login_token=login_token)

        admin_facade.remove_country(country_id)
        return redirect(url_for("admin_page.portal"))
    else:
        error = "You must be logged in to perform this operation"
        return redirect(
            url_for(
                "index_page.login",
                error=error,
            )
        )


# add route for removing an airline
@admin_page.route("/remove-airline")
def remove_airline():
    login_token = session.get("login_token")
    airline_id = int(request.values.get("airline_id"))
    admin_facade = None

    if login_token:
        admin_facade = AdministratorFacade(login_token=login_token)

        admin_facade.remove_airline(airline_id)
        return redirect(url_for("admin_page.portal"))
    else:
        error = "You must be logged in to perform this operation"
        return redirect(
            url_for(
                "index_page.login",
                error=error,
            )
        )


# add route for removing a customer
@admin_page.route("/remove-customer")
def remove_customer():
    login_token = session.get("login_token")
    customer_id = int(request.values.get("customer_id"))
    admin_facade = None

    if login_token:
        admin_facade = AdministratorFacade(login_token=login_token)

        admin_facade.remove_customer(customer_id)
        return redirect(url_for("admin_page.portal"))
    else:
        error = "You must be logged in to perform this operation"
        return redirect(
            url_for(
                "index_page.login",
                error=error,
            )
        )


# add route for removing an administrator
@admin_page.route("/remove-administrator")
def remove_admin():
    login_token = session.get("login_token")
    admin_id = int(request.values.get("admin_id"))
    admin_facade = None

    if login_token:
        admin_facade = AdministratorFacade(login_token=login_token)

        admin_facade.remove_administrator(admin_id)
        return redirect(url_for("admin_page.portal"))
    else:
        error = "You must be logged in to perform this operation"
        return redirect(
            url_for(
                "index_page.login",
                error=error,
            )
        )

views/index.py
import io

from facades import AnonymousFacade, FacadeBase
from facades.functions import (
    generate_user,
    get_airline_by_id,
    get_airline_name_by_id,
    get_country_name_by_id,
    get_user_by_user_id,
    get_user_by_username,
    get_user_role,
    get_user_role_id_by_role_name,
)
from facades.login_token import LoginToken
from flask import (
    Blueprint,
    redirect,
    render_template,
    request,
    send_file,
    session,
    url_for,
)
from more_itertools import chunked

index_page = Blueprint(
    "index_page",
    __name__,
    template_folder="../templates",
)

facade_base = FacadeBase()

# access the user logo
@index_page.route("/user-photo/<user_id>")
def server_user_photo(user_id):
    user_id = int(user_id)
    user = get_user_by_user_id(user_id)
    file_ext = user.photo_filename.split(".")[1]
    return send_file(io.BytesIO(user.photo_data), mimetype=f"image/{file_ext}")


# access the country flag logo
@index_page.route("/country-photo/<country_id>")
def serve_country_flag_image(country_id):
    country_id = int(country_id)
    country = facade_base.get_country_by_id(country_id)
    file_ext = country.country_flag_filename.split(".")[1]
    return send_file(
        io.BytesIO(country.country_flag_data), mimetype=f"image/{file_ext}"
    )


# for anonymous users
@index_page.route("/")
def index():
    login_token = session.get("login_token")
    user = None

    if login_token:
        current_user_role = get_user_role(login_token)
        user_data = LoginToken.decode_auth_token(login_token)
        user = get_user_by_username(user_data["username"])
    else:
        current_user_role = None
    flights = FacadeBase().get_all_flights()
    flights = chunked(flights, 4)
    return render_template(
        "index.html",
        current_user_role=current_user_role,
        flights=flights,
        get_airline_name_by_id=get_airline_name_by_id,
        get_country_name_by_id=get_country_name_by_id,
        get_airline_by_id=get_airline_by_id,
        get_user_by_user_id=get_user_by_user_id,
        user=user,
    )


# allow existing users to login
@index_page.route("/login", methods=["GET", "POST"])
def login():
    error = request.values.get("error")

    if request.method == "POST":
        username = request.values.get("username")
        password = request.values.get("password")

        login_token = AnonymousFacade().login(username, password)

        if login_token is None:
            return render_template("login.html", error="Invalid username or password")

        _, user_role = generate_user(login_token)

        session["login_token"] = login_token

        urls = {
            "Customer": redirect(url_for("customer_page.portal")),
            "Airline": redirect(url_for("airline_company_page.portal")),
            "Admin": redirect(url_for("admin_page.portal")),
        }
        return urls[user_role]

    return render_template("login.html", error=error)


# route to allow new users to register
@index_page.route("/register", methods=["GET", "POST"])
def register():
    if request.method == "POST":
        firstname = request.form.get("firstname")
        lastname = request.form.get("lastname")
        username = request.form.get("username")
        password = request.form.get("password")
        email = request.form.get("email")
        address = request.form.get("address")
        customer_photo = request.files.get("customer-photo")
        phone_no = request.form.get("customer-phone-no")
        credit_card_no = request.form.get("credit_card_no")

        user_role_id = get_user_role_id_by_role_name("Customer")

        # create the user first
        user = facade_base.create_new_user(
            username=username,
            password=password,
            email=email,
            user_role=user_role_id,
            photo_filename=customer_photo.filename if customer_photo else None,
            photo_data=customer_photo.read() if customer_photo else None,
        )

        # then create the customer
        facade_base.add_customer(
            firstname=firstname,
            lastname=lastname,
            address=address,
            phone_no=phone_no,
            credit_card_no=credit_card_no,
            user_id=user.id,
        )
        return redirect(url_for("index_page.login"))

    return render_template("register.html")


# end user session
@index_page.route("/logout", methods=["GET", "POST"])
def logout():
    # remove the login_token from the session and redirect to the login page
    session.pop("login_token", None)
    return redirect(url_for("index_page.login"))

templates/admin_portal.html
{% extends "base.html" %} {% block content %}
<!-- Navbar available -->
{% include "navbar.html" %}
<!--End of Navbar section-->

{% include 'admin_modals.html'%}

<!--Countries/ Destinations -->
<div style="padding: 2%">
  <div class="jumbotron">
    <h1 class="display-4">All Destinations/ Countries</h1>
    <br />
    <button
      class="btn btn-primary text-white"
      type="button"
      data-toggle="modal"
      data-target="#addCountry"
    >
      Add Country
    </button>
    {% if error %}
    <div class="alert alert-danger" role="alert">{{error}}</div>
    {% endif %}
    <br />
    <p class="lead">
      Here is a list of all Destinations/Countries For Airlines
    </p>
    {% if countries %}
    <div class="card-deck">
      {% for country in countries %}

      <!--Country Image-->
      {% if country.country_flag_filename %}
      <!--If the country has a flag image -->
      {% set country_id = country.id %} {% set country_flag_img =
      "/country-photo/" + country_id|string %}

      <!--If no profile image -->
      {% else %}
      <!--use default image -->
      {% set country_flag_img = "../static/images/no_photo.png"%}
      <!--Endif -->
      {% endif %}

      <div class="card" style="max-width: 18rem">
        <img
          class="card-img-top"
          src="{{ country_flag_img }}"
          alt="countries"
        />
        <div class="card-body">
          <h5 class="card-title">{{country.name}}</h5>

          <button
            type="button"
            class="btn btn-danger"
            data-toggle="modal"
            data-target="#deleteCountry-{{country.id}}"
          >
            Remove Country
          </button>
        </div>
      </div>

      <!-- Confirmation of deletion-->
      <div
        class="modal fade"
        id="deleteCountry-{{country.id}}"
        tabindex="-1"
        role="dialog"
        aria-labelledby="deleteCountryModal"
        aria-hidden="true"
      >
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Delete Country</h5>
              <button
                type="button"
                class="close"
                data-dismiss="modal"
                aria-label="Close"
              >
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              Are you sure you want to delete this destination? This is
              irreversible.
            </div>
            <div class="modal-footer">
              <button
                type="button"
                class="btn btn-secondary"
                data-dismiss="modal"
              >
                Close
              </button>
              <a
                class="btn btn-danger"
                href="{{ url_for('admin_page.remove_country', country_id=country.id) }}"
                >Delete Country</a
              >
            </div>
          </div>
        </div>
      </div>
      <!--End of modal-->

      {% endfor %}
    </div>

    {% else %}
    <p>No Destinations currently available! Try adding one!</p>
    {% endif %}
  </div>
</div>
<!--End of Countries/ Destinations -->

<!--Airlines -->
<div style="padding: 2%">
  <div class="jumbotron">
    <h1 class="display-4">All Airlines</h1>
    <br />
    <button
      class="btn btn-primary text-white"
      type="button"
      data-toggle="modal"
      data-target="#addAirline"
    >
      Add a new Airline
    </button>

    <br />
    <p class="lead">Here is a list of all Airlines Currently available</p>
    {% if airlines %}
    <div class="card-deck">
      <!--Get user image -->
      {% for airline in airlines %} {% set user1 =
      get_user_by_user_id(airline.user_id) %} {% if user1.photo_filename %}
      <!--If the user has a profile image -->
      {% set user_id = user1.id %} {% set img_src1 = "/user-photo/" +
      user_id|string %}

      <!--If no profile image -->
      {% else %}
      <!--use default image -->
      {% set img_src1 = "../static/images/no_photo.png"%}
      <!--Endif -->
      {% endif %}

      <div class="card" style="max-width: 18rem">
        <img class="card-img-top" src="{{ img_src1 }}" alt="airlines" />
        <div class="card-body">
          <h5 class="card-title">{{airline.name}}</h5>
          <p class="card-text">
            Country: {{get_country_name_by_id(airline.country_id)}}
          </p>

          <button
            type="button"
            class="btn btn-danger"
            data-toggle="modal"
            data-target="#deleteAirline-{{airline.id}}"
          >
            Remove Airline
          </button>
        </div>
      </div>

      <!-- Confirmation of deletion-->
      <div
        class="modal fade"
        id="deleteAirline-{{airline.id}}"
        tabindex="-1"
        role="dialog"
        aria-labelledby="deleteAirline"
        aria-hidden="true"
      >
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Delete Airline</h5>
              <button
                type="button"
                class="close"
                data-dismiss="modal"
                aria-label="Close"
              >
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              Are you sure you want to delete this airline? This is
              irreversible.
            </div>
            <div class="modal-footer">
              <button
                type="button"
                class="btn btn-secondary"
                data-dismiss="modal"
              >
                Close
              </button>
              <a
                class="btn btn-danger"
                href="{{ url_for('admin_page.remove_airline', airline_id=airline.id) }}"
                >Delete Airline</a
              >
            </div>
          </div>
        </div>
      </div>
      <!--End of modal-->

      {% endfor %}
    </div>

    {% else %}
    <p>No Airlines currently available! Try adding one!</p>
    {% endif %}
  </div>
</div>
<!--End of Airlines -->

<!--Customers -->
<div style="padding: 2%">
  <div class="jumbotron">
    <h1 class="display-4">All Customers</h1>
    <br />
    <button
      class="btn btn-primary text-white"
      type="button"
      data-toggle="modal"
      data-target="#addCustomer"
    >
      Add a new Customer
    </button>

    <br />
    <p class="lead">Here is a list of all Customers currently available</p>
    {% if customers %}
    <div class="card-deck">
      {% for customer in customers %} {% set user2 =
      get_user_by_user_id(customer.user_id) %} {% if user2.photo_filename %}
      <!--If the user has a profile image -->
      {% set user_id = user2.id %} {% set img_src2 = "/user-photo/" +
      user_id|string %}

      <!--If no profile image -->
      {% else %}
      <!--use default image -->
      {% set img_src2 = "../static/images/no_photo.png"%}
      <!--Endif -->
      {% endif %}

      <div class="card" style="max-width: 18rem">
        <img class="card-img-top" src="{{ img_src2 }}" alt="customers" />
        <div class="card-body">
          <h5 class="card-title">{{user2.username}}</h5>
          <p class="card-text">
            Full Name: {{customer.firstname + " " + customer.lastname}}
          </p>

          <button
            type="button"
            class="btn btn-danger"
            data-toggle="modal"
            data-target="#deleteCustomer-{{customer.id}}"
          >
            Remove Customer
          </button>
        </div>
      </div>

      <!-- Confirmation of deletion-->
      <div
        class="modal fade"
        id="deleteCustomer-{{customer.id}}"
        tabindex="-1"
        role="dialog"
        aria-labelledby="deleteAirline"
        aria-hidden="true"
      >
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Delete Customer</h5>
              <button
                type="button"
                class="close"
                data-dismiss="modal"
                aria-label="Close"
              >
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              Are you sure you want to delete this customer with the username:
              <b>{{user2.username}}</b>? This is irreversible.
            </div>
            <div class="modal-footer">
              <button
                type="button"
                class="btn btn-secondary"
                data-dismiss="modal"
              >
                Close
              </button>
              <a
                class="btn btn-danger"
                href="{{ url_for('admin_page.remove_customer', customer_id=customer.id) }}"
                >Delete Customer</a
              >
            </div>
          </div>
        </div>
      </div>
      <!--End of modal-->

      {% endfor %}
    </div>

    {% else %}
    <p>No Customers currently available! Try adding one!</p>
    {% endif %}
  </div>
</div>
<!--End of Customers -->

<!--Administrators -->
<div style="padding: 2%">
  <div class="jumbotron">
    <h1 class="display-4">All Administrators</h1>
    <br />
    <button
      class="btn btn-primary text-white"
      type="button"
      data-toggle="modal"
      data-target="#addAdmin"
    >
      Add Administrator
    </button>

    <br />
    <br />
    <p class="lead">Here is a list of all Administrators currently available</p>
    {% if administrators %}
    <div class="card-deck">
      {% for admin in administrators %} {% set user3 =
      get_user_by_user_id(admin.user_id) %} {% if user3.photo_filename %}
      <!--If the user has a profile image -->
      {% set user_id = user3.id %} {% set img_src3 = "/user-photo/" +
      user_id|string %}

      <!--If no profile image -->
      {% else %}
      <!--use default image -->
      {% set img_src3 = "../static/images/no_photo.png"%}
      <!--Endif -->
      {% endif %}

      <div class="card" style="max-width: 18rem">
        <img class="card-img-top" src="{{ img_src3 }}" alt="administrators" />
        <div class="card-body">
          <h5 class="card-title">{{user3.username}}</h5>
          <p class="card-text">
            Full Name: {{admin.firstname + " " + admin.lastname}}
          </p>

          {% if admin.user_id == current_logged_in_admin %}
          <button
            type="button"
            class="btn btn-danger"
            data-toggle="modal"
            data-target="#deleteAdmin-{{admin.id}}"
            disabled
          >
            Remove Admin (YOU)
          </button>
          {% else %}
          <button
            type="button"
            class="btn btn-danger"
            data-toggle="modal"
            data-target="#deleteAdmin-{{admin.id}}"
          >
            Remove Admin
          </button>
          {% endif %}
        </div>
      </div>

      <!-- Confirmation of deletion-->
      <div
        class="modal fade"
        id="deleteAdmin-{{admin.id}}"
        tabindex="-1"
        role="dialog"
        aria-labelledby="deleteAdministrator"
        aria-hidden="true"
      >
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Delete Admin</h5>
              <button
                type="button"
                class="close"
                data-dismiss="modal"
                aria-label="Close"
              >
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              Are you sure you want to delete this Administrator? This is
              irreversible.
            </div>
            <div class="modal-footer">
              <button
                type="button"
                class="btn btn-secondary"
                data-dismiss="modal"
              >
                Close
              </button>
              <a
                class="btn btn-danger"
                href="{{ url_for('admin_page.remove_admin', admin_id=admin.id) }}"
                >Delete Admin</a
              >
            </div>
          </div>
        </div>
      </div>
      <!--End of modal-->

      {% endfor %}
    </div>

    {% else %}
    <p>No Administrators currently available! Try adding one!</p>
    {% endif %}
  </div>
</div>
<!--End of Administrators -->

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Flight System Project</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
  </head>
  <body>
    {% block content %} {% endblock %}
    <script
      src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
      integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"
      integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/flights.html
<div class="container my-5">
  <!-- Jumbotron -->
  <!-- Content -->
  <div style="background-color: black">
    <div class="card-body text-white">
      <h5 class="mb-4 font-weight-bold">
        Flights currently available for booking
      </h5>
    </div>
  </div>
  <!-- Content -->

  <!-- Jumbotron -->

  <hr class="my-5" />

  {% if flights %}
  <!--Carousel Wrapper-->
  <div
    id="multi-item-example"
    class="carousel slide carousel-multi-item"
    data-ride="carousel"
  >
    {% if ticket_error %}
    <div class="alert alert-danger" role="alert">{{ticket_error}}</div>
    {% endif %}

    <!--Indicators-->
    <ol class="carousel-indicators">
      <li
        data-target="#multi-item-example"
        data-slide-to="0"
        class="active"
      ></li>
      <li data-target="#multi-item-example" data-slide-to="1"></li>
    </ol>
    <!--/.Indicators-->

    <!--Slides-->
    <div class="carousel-inner" role="listbox" id="flights-options">
      {% for flight in flights %}
      <!--Slides-->
      <div class="carousel-item active">
        {% for flight_parameters in flight %}
        <div class="col-md-3" style="float: left">
          {% set airline =
          get_airline_by_id(flight_parameters.airline_company_id) %} {% set user
          = get_user_by_user_id(airline.user_id) %} {% if user.photo_filename %}
          <!--If the user has a profile image -->
          {% set user_id = user.id %} {% set img_src = "/user-photo/" +
          user_id|string %}

          <!--If no profile image -->
          {% else %}
          <!--use default image -->
          {% set img_src = "../static/images/no_photo.png"%}
          <!--Endif -->
          {% endif %}

          <div class="card mb-2">
            <img class="card-img-top" src="{{img_src}}" alt="Card image cap" />
            <div class="card-body">
              <h4 class="card-title">
                {{get_airline_name_by_id(flight_parameters.airline_company_id)}}
              </h4>
              <p class="card-text">
                <b style="color: red">
                  Tickets Left: {{flight_parameters.remaining_tickets}}</b
                >
              </p>
              <p class="card-text">
                Origin:
                {{get_country_name_by_id(flight_parameters.origin_country_id)}}
              </p>
              <p class="card-text">
                Destination:
                {{get_country_name_by_id(flight_parameters.destination_country_id)}}
              </p>
              <p class="card-text">
                Departure Date: {{flight_parameters.departure_date}}
              </p>
              <p class="card-text">
                Landing Date: {{flight_parameters.landing_date}}
              </p>
              <a
                class="btn btn-secondary"
                href="/customer/add-ticket?flight_id={{flight_parameters.id}}"
                >Book Ticket</a
              >
            </div>
          </div>
        </div>

        {% endfor %}
      </div>
      <!--/Slides-->
      {% endfor %}
    </div>
    <!--/.Slides-->
  </div>
  <!--/.Carousel Wrapper-->
  {% else %}
  <h1>No Flights Available</h1>
  {% endif %}
</div>

templates/index.html
{% extends "base.html" %} {% block content %} {% include 'navbar.html' %}
<br />
<div style="padding: 1%">
  <!-- Flights available -->
  {% include 'flights.html' %}
  <!--End of flights section-->
</div>

{% endblock %}